# Generated by Django 2.0.6 on 2018-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_auto_20180701_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(),
        ),
    ]
