# Generated by Django 2.0.6 on 2018-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20180701_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
